- name: install homebrew cask packages
  community.general.homebrew_cask:
    name:
      - docker
      - google-chrome
      - iterm2
      - scroll-reverser
      - slack
      - stats
      - visual-studio-code
      - zoom
